# Generated by Django 2.2.6 on 2019-10-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('formas_pagamento', models.CharField(choices=[('Boleto', 'Boleto'), ('Credito', 'Credito'), ('Debito', 'Debito')], default='Boleto', max_length=2)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
