# Generated by Django 2.1.5 on 2019-10-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='formas_pagamento',
            field=models.CharField(choices=[('Boleto', 'Boleto'), ('Credito', 'Credito'), ('Debito', 'Debito')], default='Boleto', max_length=14),
        ),
    ]
